GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQzODI3NjEsImV4cCI6MTcxNDM4NjM2MSwiYXVkIjoiXCI2NjJmNDZhMmQzYjFlMmEyZWU3ODFmZWZcIiIsImlzcyI6ImxpZ2h0Y29kZXNlLmNvbSJ9.3CaqUtQPREWnFkI4WOpz5rkTXgKYo4TxUIPh6XksYHQ

### Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "lightcodese@gmail.com",
    "password": "1234"
}

### Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "lightcodese@gmail.com",
    "password": "1234"
}

### Refresh-token Route
POST http://localhost:5000/auth/refresh-token

### Logout Route
DELETE http://localhost:5000/auth/logout