GET http://localhost:5000

### Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "lightcodese@gmail.com",
    "password": "1234"
}

### Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "lightcodese@gmail.com",
    "password": "1234"
}

### Refresh-token Route
POST http://localhost:5000/auth/refresh-token

### Logout Route
DELETE http://localhost:5000/auth/logout